extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers: 
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp/data-prepper:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/data-prepper]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [otlp/data-prepper]
      processors: [batch]
  
  extensions: [pprof]
  
  telemetry:
    logs:
      level: debug